### ISSUE TITLE
Run against Xcode 12 / iOS 14

### ISSUE THREAD

**Issue by KaneCheshire** [theappbusiness/TABTestKit#115]
Leaving this issue open as a reminder to make sure we run this against Xcode 12 and iOS 14 when it's closer to coming out of beta.

We can also use this thread as a list of bugs we find if we run this on Xcode 12 in advance.

**Comment by KaneCheshire** [comment]
Initially it seems as though biometrics in the iOS 14 / Xcode 12 simulator is broken. When just running the app and manually enrolling biometrics using the normal simulator menus, clicking "log in" gives me the error:

`Domain=com.apple.LocalAuthentication Code=-1000 "UI service connection invalidated." UserInfo={NSLocalizedDescription=UI service connection invalidated.`

If this is just a simulator bug, there's not much we can do about fixing it.

**Comment by KaneCheshire** [comment]
Follow up, I also got a system crash report for "CoreAuthUI" which definitely feels like it correlates with that error above. 
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/10811515/88930848-f2838900-d273-11ea-9e13-2ba609b3583f.png">

**Comment by KaneCheshire** [comment]
Looks like it's a problem in Apple's sample code too: https://openradar.appspot.com/FB7874732

**Comment by roger-tan** [comment]
I just tested with Xcode 12 Beta 4. It seems that the issue with Biometrics has been resolved.
