### ISSUE TITLE
SPM installation

### ISSUE THREAD

**Issue by tshort15-ford** [theappbusiness/TABTestKit#127]
Hi, I've just been trying out installing TABTestKit using SPM and I get this error - any ideas?

<img width="711" alt="Screenshot 2020-08-12 at 19 24 41" src="https://user-images.githubusercontent.com/45559282/90053320-35147f00-dcd2-11ea-8c7c-7fa64969bd17.png">

I'm attempting to use v1.6.1 but this also fails with 1.5.0 and 1.6.0.

**Comment by KaneCheshire** [comment]
I think this will happen until a release next gets tagged, until then you can just make it point to `master` but that's probably a good kick up the butt for us to get a release out @zacoid55

**Comment by KaneCheshire** [comment]
Sorry, not even `master` will work until a release 🤦 it'll have to be `develop` for now. This segues  nicely into another conversation I want to have with removing `develop` and `master` just having a single `main` branch, but that's another discussion for another time!

**Comment by zacoid55** [comment]
I was waiting for a couple of changes Roger was going to put in for another release, I'll see where he's at with that now.

And yes, for this library I don't think we need develop, there's not enough people working on it

**Comment by zacoid55** [comment]
@tshort15-ford `1.7.0` is out now with Swift Package Manager support, please give it a try when you can, we'd love to hear if it works!

**Comment by tshort15-ford** [comment]
That is a quick turnaround - thanks Zac!  Seems to import fine 👍

**Comment by roger-tan** [comment]
Thanks @tshort15-ford to let us that SPM is working in your side.

**Comment by kesavaj** [comment]
Hi, I tried using SPM, but when I add TABTestKit using xcode it adds properly. but when i try to use it, it gives me a compilation error saying Missing required module Biometrics. I cannot go further can you help pls
