### ISSUE TITLE
Support pull to refresh (idea)

### ISSUE THREAD

**Issue by itsmathou** [theappbusiness/TABTestKit#133]
Hey y'all

As we were writing some tests with a pull to refresh action, I was wondering if TABTestKit could support it?
It could be implemented as follow
```
func pullToRefresh(from element: Element) {
     let firstElement = element.underlyingXCUIElement
     let start = firstElement.coordinateWithNormalizedOffset(CGVectorMake(0, 0))
     let finish = firstElement.coordinateWithNormalizedOffset(CGVectorMake(0, 6))
     start.pressForDuration(0, thenDragToCoordinate: finish)
}
```

This is just an idea as it could be useful for other people using the library 😄

**Comment by roger-tan** [comment]
That's probably a great feature to have it as it could be common action to do on a lot of apps.

**Comment by zacoid55** [comment]
I'm pretty sure we have it in there already 🙂. Let me fine you the test

**Comment by roger-tan** [comment]
@itsmathou Have you considered to use [Refreshable protocol](https://github.com/theappbusiness/TABTestKit/blob/develop/TABTestKit/Classes/Protocols/Refreshable.swift)? We released on the last release v.1.7.0

This an example that you could find [here](https://github.com/theappbusiness/TABTestKit/blob/develop/Example/TABTestKit_ExampleUITests/TableScreen.swift)

Let know us if it works on your side.

**Comment by itsmathou** [comment]
Hey @roger-tan & @zacoid55, thanks for the heads up! It works well :) Just need to be able to use 1.7.0 because of the requirement
You can close!

**Comment by roger-tan** [comment]
Thank you for responding. I will close this issue.
