### ISSUE TITLE
Tappable for Label

### ISSUE THREAD

**Issue by bartzet** [theappbusiness/TABTestKit#148]
👋  Hello

Can you please add `Tappable` to  `/TABTestKit/Classes/Elements/Label.swift`?

**Comment by zacoid55** [comment]
Heya @bartzet  - I'll endeavour to take a look into this or possibly @roger-tan or @annapiktas. In the mean time do you have any updates?

**Comment by roger-tan** [comment]
That should be possible if Label is conform to the protocol with Tappable.  Have you got chance to get this working by chance? 
When I have some free time, I could have a look to make conform to Tappable and update our example test against that.

**Comment by bartzet** [comment]
> That should be possible if Label is conform to the protocol with Tappable. 

That's correct. It needs to be implemented on the framework level though. 

When I applied the change to the framework's code I managed to make it work but it would be great if the framework could support it.

Thanks

**Comment by stefanrenne** [comment]
@bartzet That's not really how Apple intended you to use labels.
try setting `accessibilityTraits` to `.button`
And use TABKit's `Button()`
More information: https://developer.apple.com/documentation/uikit/uiaccessibility/uiaccessibilitytraits

**Comment by bartzet** [comment]
That's fine. This is what I've been doing so far. Thank you for your comments, appreciate it.
