### ISSUE TITLE
[Issue] SPM installation

### ISSUE THREAD

**Issue by kesavaj** [theappbusiness/TABTestKit#149]
Hi, I tried using SPM, but when I add TABTestKit using xcode it adds properly. but when i try to use it, it gives me a compilation error saying Missing required module Biometrics. I cannot go further can you help pls

**Comment by zacoid55** [comment]
Hello @kesavaj - I'll endeavour to take a look into this or possibly @roger-tan or @annapiktas. In the mean time do you have any updates?

**Comment by kesavaj** [comment]
@zacoid55 thanks a lot. No. Its still the same from my side. Cant get it working with SPM.

**Comment by roger-tan** [comment]
Hi @kesavaj,

Have you set up TABTestKit with the right target by chance with a UITest target?

<img width="731" alt="Screenshot 2021-04-21 at 11 26 57" src="https://user-images.githubusercontent.com/3829527/115540730-37ce6780-a296-11eb-8e3b-b5dc8f4d97ce.png">

**Comment by kesavaj** [comment]
@roger-tan That works. Thanks a lot
