### ISSUE TITLE
Use of `await` with Swift 5.5

### ISSUE THREAD

**Issue by tshort15-ford** [theappbusiness/TABTestKit#151]
Just a heads-up when compiled with the latest Swift 5.5 compiler in Xcode 13 for iOS 15 it exposes TABTestKit's use of `await` as a method name.  On Xcode 12.5 it's a warning, but an error in Xcode 13.  e.g. 

> `await` in a function that does not support concurrency

**Comment by itsmathou** [comment]
Here's a screenshot for reference. 
![Screenshot 2021-06-14 at 15 51 22](https://user-images.githubusercontent.com/38668010/121913509-5ea29a80-cd29-11eb-9a49-20bc131ac6a1.png)

Tony and I wanted to try to use Xcode 13 to check a fix from Apple

**Comment by theblixguy** [comment]
I have opened a PR to resolve this - https://github.com/theappbusiness/TABTestKit/issues/151

**Comment by itsmathou** [comment]
Thanks!
