### ISSUE TITLE
Making adjustment on the pickerWheel will fail in some scenario

### ISSUE THREAD

**Issue by TABanniefung** [theappbusiness/TABTestKit#21]
Issue on the pickerWheel:

This step here `When(I: adjust(menuScreen.picker.wheel(0), to: "Example"))` does not work in scenario when `self.view.endEditing(true)` is implemented for the pickerWheel in the app code.

The reason is that the pickerWheel is set to disappear from the screen after the user makes an adjustment on the wheel. Therefore when running the UI test, it succeeds in making the adjustment on the pickerWheel but fails on asserting the expected value that has been set.

**Comment by TABanniefung** [comment]
This step here `Then(I: adjust(otherElementsScreen.slider, to: 1))` provided in the example fails.

The reason for the assertion failure is `Element did not have the right value before timing out! Expected: 1.0, actual: 0.9971751570701599`

**Comment by KaneCheshire** [comment]
@TABanniefung these seem like two separate issues?

**Comment by KaneCheshire** [comment]
Issue #23 covers the slider issue (although I can't reproduce it!)
