### ISSUE TITLE
Test for the slider fails on the example app

### ISSUE THREAD

**Issue by TABanniefung** [theappbusiness/TABTestKit#23]
Issue on the slider:

This step here Then(I: adjust(otherElementsScreen.slider, to: 1)) provided in the example fails.

The reason for the assertion failure is Element did not have the right value before timing out! Expected: 1.0, actual: 0.9971751570701599

**Comment by KaneCheshire** [comment]
I haven't been able to reproduce this @TABanniefung, what simulator/iOS version are you running this on for this to happen?

**Comment by TABanniefung** [comment]
it is failing on iphone XR OS 12.4

**Comment by zacoid55** [comment]
@TABanniefung could you give this another go, please? You'll need to be pointing to develop like you were doing before we released recently

**Comment by KaneCheshire** [comment]
Fixing this in #38, by just removing the assertions. Apple say they can't guarantee it will be exact and I've started running into this issue too.

I tried setting the simulator to different resolutions in case it was an issue being on a retina Mac screen but didn't seem to make any difference, and it wouldn't really be fair to expect people to have to set that just to get tests to pass.
