### ISSUE TITLE
Disable Bitcode in packaging

### ISSUE THREAD

**Issue by Neil3079** [theappbusiness/TABTestKit#39]
TABTestKit ships with Bitcode enabled, this is a production code feature and not fit for a testing library (in fact XCTest doesn't even support bitcode). This can cause compilation areas in certain projects that need to be worked around

suggest adding `ENABLE_BITCODE` to `NO` in the pod spec.

**Comment by KaneCheshire** [comment]
Good shout, I should have thought about this since I had to do the same thing for PixelTest.

**Comment by KaneCheshire** [comment]
This should be fixed now in #47 (1.1.0), any problems please let me know or raise a new issue.
