### ISSUE TITLE
Investigate if TravisCI supports running on multiple iOS versions (it should!)

### ISSUE THREAD

**Issue by KaneCheshire** [theappbusiness/TABTestKit#46]
Since we're having issues with iOS 12 to iOS 13, it would be really beneficial to have CI run tests on both so we can be sure fixing one doesn't break the other

**Comment by KaneCheshire** [comment]
Also just a thought, even better would be to have it run on two different versions of Xcode as well, since it can be really easy to accidentally miss out a `return` in Xcode 11 which won't compile on Xcode 10, even though they're both Swift 5.

**Comment by zacoid55** [comment]
@KaneCheshire you have no idea how much "since it can be really easy to accidentally miss out a return in Xcode 11 which won't compile on Xcode 10, even though they're both Swift 5." helped me understand why something won't build hahaha
