### ISSUE TITLE
Add support for datepicker

### ISSUE THREAD

**Issue by TABanniefung** [theappbusiness/TABTestKit#55]
public struct DatePicker: Element {
	
	public let id: String?
	public let index: Int
	public let parent: Element
	public let type: XCUIElement.ElementType = .datePicker
	
	/// Returns the number of wheels the picker contains.
	public var numberOfWheels: Int { return underlyingXCUIElement.pickerWheels.count }
	
	public init(id: String, index: Int = 0, parent: Element = App.shared) {
		self.id = id
		self.index = index
		self.parent = parent
	}
	
	public func wheel(_ index: Int) -> Wheel {
		return Wheel(index: index, picker: self)
	}
}

public extension DatePicker {
	
	struct Wheel: Element, ValueRepresentable, Adjustable {
		
		public let id: String? = nil
		public let index: Int
		public let parent: Element
		public let type: XCUIElement.ElementType = .pickerWheel
		public var value: String { return underlyingXCUIElement.value as? String ?? "" }
		
		public init(index: Int, picker: DatePicker) {
			self.index = index
			self.parent = picker
		}
		
		public func adjust(to newValue: String) {
			underlyingXCUIElement.adjust(toPickerWheelValue: newValue)
		}
		
	}
	
}

**Comment by zacoid55** [comment]
Is this something that could be raised as a PR, @TABanniefung?

**Comment by TABanniefung** [comment]
@zacoid55 I have no permission 😰
