### ISSUE TITLE
backgroundTheApp() does not run for iOS 13

### ISSUE THREAD

**Issue by anyfuncyo** [theappbusiness/TABTestKit#67]
Reason: App is not suspended on background https://forums.developer.apple.com/thread/124596

Solution: update `XCTAssert(wait(for: .runningBackgroundSuspended, timeout: 10))` to `.runningBackground` for iOS 13

**Comment by KaneCheshire** [comment]
This should be a pretty easy one to create a PR for if you get some time. Maybe tap up one of the iOS devs on your project if you need some help writing code that only works for iOS 13 and then falls back to some other code
