### ISSUE TITLE
Support scrolling a Scrollable element until some element has a particular _value_

### ISSUE THREAD

**Issue by KaneCheshire** [theappbusiness/TABTestKit#72]
At the moment, it's only possible to scroll until some element is in a particular _state_, i.e. visible, hittable etc, but it would be good if we could also scroll an element until something has a particular value.

A use case for this, is scrolling a screen until a page indicator has a particular value of something like "page 2 of 2".

**Comment by annapiktas** [comment]
I've added the scroll func, @bengilroy kindly agreed to add an element with changing value to an example app so I can test the func. We are both on hols next week so this will be on hold for a bit.

**Comment by annapiktas** [comment]
The issue was resolved and merged to develop branch.
