### ISSUE TITLE
Add a test for relaunching the app

### ISSUE THREAD

**Issue by KaneCheshire** [theappbusiness/TABTestKit#79]
Since a bug was fixed in #75 about the background state not working correctly in iOS 13 (at least in the sim) it would have been nice to catch that earlier with a test rather than in someone's project, so I think we just need one of the tests to relaunch the app to avoid a regression.

**Comment by annapiktas** [comment]
Note: `.runningBackgroundSuspended`  doesn't happen from iOS 13 locally on my machine  on Xcode 11.4.1  as per [article](https://developer.apple.com/forums/thread/124596) but on Travis it doesn't seem to happen from iOS 12(possibly 12.4) on Xcode 10.3 The issue doesn't seem to be linked to Swift version, neither extending the timeout to 3 minutes on Travis solves the issue. However when`.runningBackground`  process is active the CPU goes down to zero on Xcode Instruments so it looks like the background processes get suspended somehow.
